name: youtube_browser
description: A YouTube-only browser with PiP mode.
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.1.5
  audio_session: ^0.2.2
  permission_handler: ^11.3.0
  wakelock_plus: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
